name: cosim120
channels:
  - conda-forge
  - defaults
dependencies:
  - assimulo=3.2.5=py36h6ea5667_0
  - certifi=2021.5.30=py36haa95532_0
  - fmilib=2.3=h0e60522_0
  - intel-openmp=2021.3.0=h57928b3_3372
  - libblas=3.9.0=11_win64_mkl
  - libcblas=3.9.0=11_win64_mkl
  - libiconv=1.16=he774522_0
  - liblapack=3.9.0=11_win64_mkl
  - libxml2=2.9.12=hf5bbc77_0
  - libxslt=1.1.33=h65864e5_2
  - lxml=4.6.3=py36hf8cb5f9_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2021.3.0=hb70f87d_564
  - msys2-conda-epoch=20160418=1
  - numpy=1.19.5=py36h4b40d73_2
  - pandas=1.1.5=py36hd77b12b_0
  - pip=21.0.1=py36haa95532_0
  - pyfmi=2.9.2=py36h14b15b0_0
  - python=3.6.13=h3758d61_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.1=pyhd3eb1b0_0
  - scipy=1.5.3=py36h27d303f_1
  - setuptools=58.0.4=py36haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - sundials=5.7.0=h39d44d4_0
  - tbb=2021.3.0=h2d74725_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py36h7fe50ca_0
  - zlib=1.2.11=h62dcd97_1010
  - pip:
    - absl-py==0.14.0
    - astunparse==1.6.3
    - cached-property==1.5.2
    - cachetools==4.2.2
    - charset-normalizer==2.0.6
    - clang==5.0
    - cloudpickle==2.0.0
    - cosim==0.12.1
    - cycler==0.10.0
    - dataclasses==0.8
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.40.0
    - gym==0.20.0
    - h5py==3.1.0
    - idna==3.2
    - importlib-metadata==4.8.1
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pillow==8.3.2
    - plotly==4.9.0
    - protobuf==3.18.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.7.2
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.6.0
    - tensorflow-gpu==2.6.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.7
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.5.0
prefix: C:\Users\akhan147\Anaconda3\envs\cosim120
